# Generated by Django 5.2 on 2025-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_alter_doctor_category_alter_doctor_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mobile_no', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Surgeon', 'Surgeon'), ('Wardboy', 'Wardboy'), ('Cleaner', 'Cleaner'), ('Receptionist', 'Receptionist'), ('HR', 'HR'), ('Lab Assistant', 'Lab Assistant'), ('Pharmacist', 'Pharmacist'), ('Radiologist', 'Radiologist'), ('Anesthetist', 'Anesthetist'), ('Pathologist', 'Pathologist'), ('Physiotherapist', 'Physiotherapist'), ('IT Support', 'IT Support'), ('Security Guard', 'Security Guard'), ('Accountant', 'Accountant'), ('Medical Technician', 'Medical Technician'), ('Ambulance Driver', 'Ambulance Driver'), ('Dietitian', 'Dietitian'), ('Billing Executive', 'Billing Executive'), ('Operation Theatre Assistant', 'Operation Theatre Assistant'), ('Front Desk Executive', 'Front Desk Executive'), ('Maintenance Staff', 'Maintenance Staff'), ('Medical Records Officer', 'Medical Records Officer'), ('Blood Bank Staff', 'Blood Bank Staff')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/employees/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
