# Generated by Django 5.2 on 2025-04-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_doctor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
