# Generated by Django 5.2 on 2025-04-12 17:10

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_doctor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.ForeignKey(default=myapp.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='doctors', to='myapp.doctorcategory'),
        ),
    ]
